/**
 * @file Automatically generated by barrelsby.
 */

// Re-export individual modules to maintain compatibility without barrel patterns

// From common.ts - Core API response and query types (manually added)
export type { OpenAlexResponse, QueryParams, SampleParams, StatsParams, GroupParams, BaseAutocompleteOptions, NGram, TextAnalysis, GroupedResponse } from "./entities/common";
export { OpenAlexResponseSchema, QueryParamsSchema, SampleParamsSchema, StatsParamsSchema, GroupParamsSchema, BaseAutocompleteOptionsSchema, NGramSchema, TextAnalysisSchema, createGroupedResponseSchema } from "./entities/common";

// From bookmark.ts
export type { BookmarkMetadata, Bookmark } from "./bookmark";
export { BookmarkMetadataSchema, BookmarkSchema } from "./bookmark";

// From concepts.ts
export type { ConceptRelationship, ConceptGraphEdge } from "./concepts";
export { createConceptGraphEdge, isConceptRelationship } from "./concepts";

// From expansion-settings.ts
export type {
  ExpansionTarget,
  ExpansionOptions,
  SortCriteria,
  FilterOperator,
  FilterCriteria,
  ExpansionSettings,
  PropertyType,
  PropertyDefinition,
  EntityTypeProperties
} from "./expansion-settings";
export {
  ENTITY_PROPERTIES,
  DEFAULT_EXPANSION_SETTINGS,
  getPropertiesForTarget,
  getDefaultSettingsForTarget,
  validateFilterCriteria
} from "./expansion-settings";

// From grants.ts
export type { GrantRelationship, GrantGraphEdge } from "./grants";
export { createGrantGraphEdge, isGrantRelationship } from "./grants";

// From graph-index-types.ts
export type {
  CompletenessStatus,
  GraphNodeRecord,
  AuthorPosition,
  PublicationVersion,
  GraphEdgeRecord,
  GraphNodeInput,
  GraphEdgeInput,
  EdgePropertyFilter,
  EdgeDirectionFilter,
  NeighborQueryOptions,
  SubgraphResult,
  GraphStatistics
} from "./graph-index-types";
export {
  GRAPH_INDEX_DB_NAME,
  GRAPH_INDEX_DB_VERSION,
  GRAPH_INDEX_TABLES,
  NODE_INDEXES,
  EDGE_INDEXES
} from "./graph-index-types";

// From graph-types.ts
export type {
  Position,
  ExternalIdentifier,
  GraphNode,
  EdgeDirection,
  GraphEdge,
  GraphLayout,
  GraphEvents,
  GraphOptions,
  EntityIdentifier,
  ProviderType,
  SearchOptions,
  SearchResult,
  GraphData,
  GraphCache,
  GraphStats,
  Community,
  ForceLink,
  ForceSimulationNode,
  ForceSimulationTask,
  Position3D,
  ViewMode,
  ControlMode,
  GraphNode3D,
  GraphEdge3D,
  BoundingBox3D,
  CameraState3D,
  CameraAnimation,
  ControlSettings,
  LODConfig,
  DetailLevel,
  PerformanceMetrics3D,
  GraphData3D,
  Visualization3DPreferences
} from "./graph-types";
export {
  isPosition3D,
  isGraphNode3D,
  isCameraState3D
} from "./graph-types";

// From keywords.ts
export type { KeywordRelationship, KeywordGraphEdge } from "./keywords";
export { createKeywordGraphEdge, isKeywordRelationship } from "./keywords";

// From relationships.ts
export { RelationType } from "./relationships";

// From repositories.ts
export type { RepositoryRelationship, RepositoryGraphEdge } from "./repositories";
export { createRepositoryGraphEdge, isRepositoryRelationship } from "./repositories";

// From roles.ts
export type { RoleRelationship, RoleGraphEdge } from "./roles";
export { createRoleGraphEdge, isRoleRelationship } from "./roles";

// From topics.ts
export type { EnhancedTopicRelationship, EnhancedTopicGraphEdge } from "./topics";
export { createEnhancedTopicGraphEdge, isEnhancedTopicRelationship } from "./topics";

// From traversal-types.ts
export type {
  WeightableEdgeProperty,
  WeightFunction,
  WeightConfig,
  TraversalDirection,
  TraversalOptions,
  WeightedPathResult,
  PathfindingOptions
} from "./traversal-types";

// From entities module
export type { EntityType, OpenAlexEntity } from "./entities";
export type { BaseEntity, Author, Work, Institution, Source, Publisher, Funder, Concept, Domain, Field, Subfield, Topic, Keyword, InstitutionEntity, Authorship } from "./entities";
export type { RelationshipQueryConfig } from "./entities/relationship-queries";
export type { GraphProvenance } from "./graph/graph-list";

// Export field types for entity detail components
export type {
  BaseEntityField,
  EntityWithWorksField,
  AuthorField,
  WorkField,
  SourceField,
  InstitutionField,
  ConceptField,
  TopicField,
  PublisherField,
  FunderField,
  KeywordField
} from "./entities/entities";
export { ENTITY_TYPES } from "./entities";

// Export filter types that were previously available through barrels
export type {
  WorksFilters,
  AuthorsFilters,
  SourcesFilters,
  InstitutionsFilters,
  TopicsFilters,
  ConceptsFilters,
  PublishersFilters,
  FundersFilters,
  KeywordsFilters,
  BaseEntityFilters,
  BaseEntityWithTopicsFilters,
  EntityFilters
} from "./entities/filters";

// Export author-specific types that were previously available through barrels
export type {
  AuthorGroupingOptions,
  AuthorCollaboratorsFilters,
  AuthorAutocompleteOptions,
  AuthorWorksFilters,
  AuthorSearchOptions,
  GroupByResult
} from "./entities";
export {
  getEntityRelationshipQueries,
  getInboundQueries,
  getOutboundQueries,
  hasInboundQueries,
  hasOutboundQueries,
  ENTITY_RELATIONSHIP_QUERIES
} from "./entities";
export {
  ENTITY_METADATA,
  getEntityMetadata,
  getEntitySingularForm,
  getEntityIdPrefix,
  getEntityRoutePath,
  getEntityIcon,
  getEntityColor,
  getEntityDisplayName,
  getEntityPlural,
  toEntityType,
  toSingularForm,
  isEntityType,
  detectEntityType
} from "./entities";
export { getEntityType, isOpenAlexEntity } from "./entities";
export { validateWithSchema, trustObjectShape, extractPropertyValue } from "./entities";
export { isRecord } from "./entities/utils";
export { isOpenAlexId } from "./entities";
export type { OpenAlexError, AutocompleteResult } from "./entities";

// Export graph-list types that were previously available through barrels
export type {
  GraphListNode,
  AddToGraphListParams,
  PruneGraphListResult
} from "./graph/graph-list";
export {
  GRAPH_LIST_CONFIG
} from "./graph/graph-list";


// Export concept-specific types
export type {
  ConceptsQueryParams,
  ConceptSearchOptions
} from "./entities/concepts";


// Export OpenAlex ID and base entity types
export type {
  OpenAlexId
} from "./entities/base";

// Export core graph algorithm types
export type {
  Node,
  Edge,
  NodeBase,
  EdgeBase,
  ReadableGraph
} from "./graph-algorithms";

