// Automatically generated by barrelsby.

export type { EntityType, OpenAlexEntity } from "./entities";
export type { BaseEntity, Author, Work, Institution, Source, Publisher, Funder, Concept, Domain, Field, Subfield, Topic, Keyword, InstitutionEntity, Authorship } from "./entities";

// Export field types for entity detail components
export type {
  BaseEntityField,
  EntityWithWorksField,
  AuthorField,
  WorkField,
  SourceField,
  InstitutionField,
  ConceptField,
  TopicField,
  PublisherField,
  FunderField,
  KeywordField
} from "./entities";
export { ENTITY_TYPES } from "./entities";

// Export field constants for API validation
export {
  BASE_ENTITY_FIELDS,
  ENTITY_WITH_WORKS_FIELDS,
  AUTHOR_FIELDS,
  WORK_FIELDS,
  SOURCE_FIELDS,
  INSTITUTION_FIELDS,
  CONCEPT_FIELDS,
  TOPIC_FIELDS,
  PUBLISHER_FIELDS,
  FUNDER_FIELDS,
  KEYWORD_FIELDS
} from "./entities";

// Export filter types that were previously available through barrels
export type {
  WorksFilters,
  AuthorsFilters,
  SourcesFilters,
  InstitutionsFilters,
  TopicsFilters,
  ConceptsFilters,
  PublishersFilters,
  FundersFilters,
  KeywordsFilters,
  BaseEntityFilters,
  BaseEntityWithTopicsFilters,
  EntityFilters
} from "./filters";

// Export author-specific types that were previously available through barrels
export type {
  AuthorGroupingOptions,
  AuthorCollaboratorsFilters,
  AuthorAutocompleteOptions,
  AuthorWorksFilters,
  AuthorSearchOptions,
  GroupByResult
} from "./authors";
export {
  getEntityRelationshipQueries,
  getInboundQueries,
  getOutboundQueries,
  hasInboundQueries,
  hasOutboundQueries
} from "./relationship-queries";
export { ENTITY_RELATIONSHIP_QUERIES } from "./relationship-queries-registry";
export {
  ENTITY_METADATA,
  getEntityMetadata,
  getEntitySingularForm,
  getEntityIdPrefix,
  getEntityRoutePath,
  getEntityIcon,
  getEntityColor,
  getEntityDisplayName,
  getEntityPlural,
  toEntityType,
  toSingularForm,
  isEntityType,
  detectEntityType
} from "./entity-metadata";
export { getEntityType, isOpenAlexEntity } from "./type-guards";
export { validateWithSchema, trustObjectShape, extractPropertyValue, isRecord } from "./utils";
export { isOpenAlexId } from "./validation";
export type { OpenAlexError, AutocompleteResult, AutocompleteBaseResult, OpenAlexResponse, QueryParams, SampleParams, StatsParams, GroupParams, BaseAutocompleteOptions, NGram, TextAnalysis, TextAnalysisNamedRef, TextAnalysisKeyword, TextAnalysisTopic, TextAnalysisConcept, TextAnalysisResponse, GroupedResponse } from "./common";
export { OpenAlexResponseSchema, QueryParamsSchema, SampleParamsSchema, StatsParamsSchema, GroupParamsSchema, BaseAutocompleteOptionsSchema, NGramSchema, TextAnalysisSchema, createGroupedResponseSchema, AutocompleteBaseResultSchema, AutocompleteResultSchema, AutocompleteBaseResponseSchema, AutocompleteResponseSchema, TextAnalysisNamedRefSchema, TextAnalysisKeywordSchema, TextAnalysisTopicSchema, TextAnalysisConceptSchema, TextAnalysisResponseSchema } from "./common";

// Per-entity Zod schemas for runtime validation of OpenAlex API responses
export { baseEntitySchema, entityWithWorksSchema, workSchema, authorSchema, sourceSchema, institutionSchema, conceptSchema, topicSchema, publisherSchema, funderSchema, keywordSchema, domainSchema, fieldSchema, subfieldSchema, openAlexResponseSchema, staticDataSchema, apiResponseSchema } from "./schemas";

// Export type definitions previously imported from deeper barrel-policy-violating paths
export type { OpenAlexId } from "./base";
export type { ConceptsQueryParams, ConceptSearchOptions } from "./concepts";
export type { RelationshipQueryConfig } from "./relationship-queries";